apiVersion: kink.meln5674.github.com/v0
kind: Config
kubernetes:
  context:
    namespace: rke2
kubectl:
  command: [bin/kubectl]
helm:
  command: [bin/helm]
release:
  upgradeFlags:
  - --timeout=1h
  - --create-namespace
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    worker.securityContext.privileged: "true"
    controlplane.replicaCount: "3"
    worker.replicaCount: "2"
    controlplane.persistence.enabled: "true"
    worker.persistence.enabled: "true" 
    rke2.enabled: "true"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
    controlplane.extraArgs[0]: '--disable=rke2-ingress-nginx'
    controlplane.extraArgs[1]: '--disable=rke2-metrics-server'

    controlplane.ingress.enabled:  "true"
    controlplane.ingress.hosts[0]: "rke2.cluster.local"
    controlplane.ingress.className: nginx
    controlplane.ingress.annotations.nginx\.ingress\.kubernetes\.io/backend-protocol: "HTTPS"

    loadBalancer.enabled: 'true'
    loadBalancer.service.type: 'NodePort'
    kubeconfig.enabled: 'true'

    loadBalancer.ingress.enabled: 'true'
    loadBalancer.ingress.classMappings[0].guestClassName: nginx
    loadBalancer.ingress.classMappings[0].className: nginx
    loadBalancer.ingress.classMappings[0].annotations.nginx\.ingress\.kubernetes\.io/backend-protocol: "HTTPS"

    'registries.mirrors.docker\.io.endpoint[0]': http://proxy-registry.default:5000
    'registries.mirrors.registry-1\.docker\.io.endpoint[0]': http://proxy-registry.default:5000
    'registries.mirrors.index\.docker\.io.endpoint[0]': http://proxy-registry.default:5000
  setString:
    controlplane.ingress.annotations.nginx\.ingress\.kubernetes\.io/ssl-passthrough: "true"
    loadBalancer.ingress.classMappings[0].hostPort.httpsPort: '443'
    loadBalancer.ingress.classMappings[0].annotations.nginx\.ingress\.kubernetes\.io/ssl-passthrough: "true"
