apiVersion: kink.meln5674.github.com/v0
kind: Config
kubernetes:
  context:
    namespace: rke2
release:
  upgradeFlags:
  - --timeout=1h
  - --create-namespace
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    worker.securityContext.privileged: "true"
    controlplane.replicaCount: "3"
    worker.replicaCount: "2"
    controlplane.persistence.enabled: "true"
    worker.persistence.enabled: "true" 
    rke2.enabled: "true"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
    controlplane.extraArgs[0]: '--disable=rke2-ingress-nginx'
    controlplane.extraArgs[1]: '--disable=rke2-metrics-server'

    loadBalancer.enabled: 'true'
    loadBalancer.service.type: 'NodePort'
    kubeconfig.enabled: 'true'

    loadBalancer.ingress.enabled: 'true'
    loadBalancer.ingress.classMappings[0].guestClassName: nginx
    loadBalancer.ingress.classMappings[0].className: nginx
    loadBalancer.ingress.classMappings[0].annotations.nginx\.ingress\.kubernetes\.io/backend-protocol: "HTTPS"
  setString:
    loadBalancer.ingress.classMappings[0].hostPort.httpsPort: '443'
    loadBalancer.ingress.classMappings[0].annotations.nginx\.ingress\.kubernetes\.io/ssl-passthrough: "true"
