{{- if and .Values.kubeconfig.enabled .Values.kubeconfig.job.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kink.kubeconfig.serviceAccountName" . }}
  labels:
    {{- include "kink.kubeconfig.labels" . | nindent 4 }}
  {{- with .Values.kubeconfig.job.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
