{{- define "kink.config" -}}
fullname: {{ include "kink.fullname" . }}
controlplane.fullname: {{ include "kink.controlplane.fullname" . }}
controlplane.port: '{{ .Values.controlplane.service.api.port }}'
controlplane.hostname: |-
  {{ if .Values.controlplane.ingress.enabled }}
  {{- index .Values.controlplane.ingress.hosts 0 }}
  {{- else if .Values.controlplane.nodeportHost }}
  {{- .Values.controlplane.nodeportHost }}
  {{- end }}
controlplane.isNodePort: |-
  {{ if .Values.controlplane.ingress.enabled }}
  false
  {{- else if .Values.controlplane.nodeportHost }}
  true
  {{- else }}
  false
  {{- end }}
load-balancer.fullname: {{ include "kink.load-balancer.fullname" . }}
lb-manager.fullname: {{ include "kink.lb-manager.fullname" . }}
labels: '{{ include "kink.labels" . | fromYaml | toJson }}'
selectorLabels: '{{ include "kink.selectorLabels" . | fromYaml | toJson }}'
controlplane.labels: '{{ include "kink.controlplane.labels" . | fromYaml | toJson }}'
controlplane.selectorLabels: '{{ include "kink.controlplane.selectorLabels" . | fromYaml | toJson }}'
worker.labels: '{{ include "kink.worker.labels" . | fromYaml | toJson }}'
worker.selectorLabels: '{{ include "kink.worker.selectorLabels" . | fromYaml | toJson }}'
load-balancer.labels: '{{ include "kink.load-balancer.labels" . | fromYaml | toJson }}'
load-balancer.annotations: '{{ .Values.loadBalancer.service.annotations | toJson }}'
rke2.enabled: '{{ .Values.rke2.enabled }}'
{{- end -}}


apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kink.fullname" . }}
  labels:
    {{ include "kink.labels" . | nindent 4 }}
data:
  {{- include "kink.config" . | nindent 2 }}
  config.json: '{{- include "kink.config" . | fromYaml | toJson }}'
