apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kink.fullname" . }}-registries
  labels:
    {{ include "kink.labels" . | nindent 4 }}
data:
  registries.yaml.tpl: |
    {{- .Values.registries | toYaml | nindent 4 }}
