apiVersion: kink.meln5674.github.com/v0
kind: Config
kubernetes:
  context:
    namespace: k3s-single
release:
  upgradeFlags:
  - --timeout=1h
  - --create-namespace
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    controlplane.replicaCount: "1"
    controlplane.persistence.enabled: "true"
    controlplane.defaultTaint: "false"
    worker.replicaCount: "0"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
    controlplane.extraArgs[0]: '--disable=traefik'

    loadBalancer.enabled: 'true'
    kubeconfig.enabled: 'true'

    loadBalancer.ingress.enabled: 'true'
    loadBalancer.ingress.classMappings[0].guestClassName: nginx
    loadBalancer.ingress.classMappings[0].className: nginx
  setString:
    loadBalancer.ingress.classMappings[0].hostPort.httpPort: '80'
