apiVersion: kink.meln5674.github.com/v0
kind: Config
kubernetes:
  context:
    namespace: k3s-single
release:
  upgradeFlags:
  - --timeout=1h
  - --create-namespace
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    controlplane.replicaCount: "1"
    controlplane.persistence.enabled: "true"
    controlplane.defaultTaint: "false"
    worker.replicaCount: "0"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
    controlplane.extraArgs[0]: '--disable=traefik'
