apiVersion: kink.meln5674.github.com/v0
kind: Config
kubernetes:
  context:
    namespace: k3s-ha
release:
  upgradeFlags:
  - --timeout=1h
  - --create-namespace
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    worker.securityContext.privileged: "true"
    controlplane.replicaCount: "3"
    worker.replicaCount: "2"
    controlplane.persistence.enabled: "true"
    worker.persistence.enabled: "true"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
    controlplane.extraArgs[0]: '--disable=traefik'
    controlplane.service.type: NodePort
    controlplane.nodeportHost: localhost

    loadBalancer.enabled: 'true'
    kubeconfig.enabled: 'true'
    loadBalancer.ingress.enabled: 'true'
    loadBalancer.ingress.classMappings[0].guestClassName: nginx
    loadBalancer.ingress.classMappings[0].className: nginx
    loadBalancer.ingress.classMappings[0].nodePort.namespace: default
    loadBalancer.ingress.classMappings[0].nodePort.name: ingress-nginx-controller
    loadBalancer.ingress.classMappings[0].nodePort.httpsPort: https
    loadBalancer.ingress.classMappings[0].annotations.nginx\.ingress\.kubernetes\.io/backend-protocol: "HTTPS"
    loadBalancer.ingress.static[0].className: nginx
    loadBalancer.ingress.static[0].annotations.nginx\.ingress\.kubernetes\.io/backend-protocol: "HTTPS"
    loadBalancer.ingress.static[0].hosts[0].host: wordpress.k3s-ha.ingress.outer
    loadBalancer.ingress.static[0].hosts[0].tls: 'true'
    loadBalancer.ingress.static[0].hosts[0].paths[0].path: /
    loadBalancer.ingress.static[0].hosts[0].paths[0].pathType: Prefix
    loadBalancer.ingress.static[0].nodePort.namespace: default
    loadBalancer.ingress.static[0].nodePort.name: wordpress
    loadBalancer.ingress.static[0].nodePort.port: https
  setString:
    loadBalancer.ingress.classMappings[0].annotations.nginx\.ingress\.kubernetes\.io/ssl-passthrough: "true"
    loadBalancer.ingress.static[0].host[0].annotations.nginx\.ingress\.kubernetes\.io/ssl-passthrough: "true"
