apiVersion: kink.meln5674.github.com/v0
Kind: Config
release:
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    worker.securityContext.privileged: "true"
    controlplane.replicaCount: "3"
    worker.replicaCount: "2"
    controlplane.persistence.enabled: "true"
    worker.persistence.enabled: "true"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
