apiVersion: kink.meln5674.github.com/v0
kind: Config
kubernetes:
  context:
    namespace: k3s-single
kubectl:
  command: [bin/kubectl]
helm:
  command: [bin/helm]
release:
  upgradeFlags:
  - --timeout=1h
  set:
    image.pullPolicy: Never
    controlplane.securityContext.privileged: "true"
    controlplane.replicaCount: "1"
    controlplane.persistence.enabled: "true"
    controlplane.defaultTaint: "false"
    worker.replicaCount: "0"
    sharedPersistence.enabled: "true"
    sharedPersistence.storageClassName: "shared-local-path"
    controlplane.extraArgs[0]: '--disable=traefik'
    controlplane.extraArgs[1]: '--disable=servicelb'

    fileGateway.enabled: 'true'
    loadBalancer.enabled: 'true'
    loadBalancer.service.type: 'NodePort'
    kubeconfig.enabled: 'true'

    loadBalancer.ingress.enabled: 'true'
    loadBalancer.ingress.classMappings[0].guestClassName: nginx
    loadBalancer.ingress.classMappings[0].className: nginx
    loadBalancer.ingress.static[0].className: nginx
    loadBalancer.ingress.static[0].hosts[0].host: smoke-test.k3s-single.ingress.outer
    loadBalancer.ingress.static[0].hosts[0].paths[0].path: /
    loadBalancer.ingress.static[0].hosts[0].paths[0].pathType: Prefix
    loadBalancer.ingress.static[0].hostPort: 9080
  setString:
    loadBalancer.ingress.classMappings[0].hostPort.httpPort: '80'
