apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kink-test.fullname" . }}
  labels:
    {{- include "kink-test.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "kink-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kink-test.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kink-test.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          workingDir: {{ .Values.sourceMount.containerPath }}/{{ .Values.sourceMount.subdir }}
          command: [tail, -f, /dev/null]
          env:
          - name: SHELL
            value: /bin/bash
          - name: GOCOVERDIR
            value: {{ .Values.gocoverage.dir }}
          - name: KINK_IT_IN_CLUSTER
            value: '1'
          - name: KINK_IT_IS_CI
            value: '{{ if .Values.testOpts.ci }}1{{ end }}'
          - name: KINK_IT_DEV_MODE
            value: '{{ if .Values.testOpts.devMode }}1{{ end }}'
          - name: KINK_IT_STATE
            value: '{{ .Values.testOpts.state | toJson }}'
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - name: src
            mountPath: {{ .Values.sourceMount.containerPath }}
          - name: docker
            mountPath: /var/run/docker.sock
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: src
        hostPath:
          path: {{ .Values.sourceMount.hostPath }}
      - name: docker
        hostPath:
          path: /var/run/docker.sock
          type: Socket
