apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kink.controlplane.fullname" . }}-system-charts
  labels:
    {{- include "kink.controlplane.labels" . | nindent 4 }}
data:
  local-storage.yaml.skip: |
  kink-local-storage.yaml: |
    apiVersion: helm.cattle.io/v1
    kind: HelmChart
    metadata:
      name: local-path-provisioner
      namespace: kube-system
    spec:
      bootstrap: true
      valuesContent: |
        image:
          repository: {{ .Values.image.repository }}
          tag: {{ .Values.image.tag | default .Chart.AppVersion }}
        nodePathMap: []
        storageClassConfigs:
          standard:
            storageClass:
              create: true
              defaultClass: true
              reclaimPolicy: Delete
              defaultVolumeType: hostPath
              volumeBindingMode: WaitForFirstConsumer
            nodePathMap:
            - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
              paths:
                - /opt/local-path-provisioner
          {{- if or .Values.sharedPersistence.enabled .Values.sharedPersistence.enabledWithoutStorage }}
          shared-local-path:
            storageClass:
              create: true
              defaultClass: false
              reclaimPolicy: Delete
              defaultVolumeType: hostPath
              volumeBindingMode: Immediate
            sharedFileSystemPath: /opt/shared-local-path-provisioner
          {{- end }}
      # chartContent: Injected by init container

