{{- $ports := list "api" "kubelet-metrics" "etcd-client" "etcd-peer" }}
{{- if .Values.rke2.enabled }}
{{- $ports = concat $ports (list "rke2-discover") }}
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kink.controlplane.fullname" . }}
  labels:
    {{- include "kink.controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlplane.service.type }}
  ports:
    {{- range $port := $ports }}
    - port: {{ (index $.Values.controlplane.service $port).port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $port }}
    {{- end }}
  selector:
    {{- include "kink.controlplane.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kink.controlplane.fullname" . }}-headless
  labels:
    {{- include "kink.controlplane.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  type: {{ .Values.controlplane.service.type }}
  publishNotReadyAddresses: true
  ports:
    {{- range $port := $ports }}
    - port: {{ (index $.Values.controlplane.service $port).port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $port }}
    {{- end }}
  selector:
    {{- include "kink.controlplane.selectorLabels" . | nindent 4 }}

