apiVersion: v1
kind: Service
metadata:
  name: {{ include "kink.worker.fullname" . }}
  labels:
    {{- include "kink.worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.worker.service.type }}
  ports:
    {{- range $port := list "kubelet-metrics" }}
    - port: {{ (index $.Values.worker.service $port).port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $port }}
    {{- end }}
    {{- range $port := .Values.worker.extraPorts }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}

  selector:
    {{- include "kink.worker.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kink.worker.fullname" . }}-headless
  labels:
    {{- include "kink.worker.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  type: ClusterIP
  publishNotReadyAddresses: true
  ports:
    {{- range $port := list "kubelet-metrics" }}
    - port: {{ (index $.Values.worker.service $port).port }}
      targetPort: {{ $port }}
      protocol: TCP
      name: {{ $port }}
    {{- end }}
    {{- range $port := .Values.worker.extraPorts }}
    - port: {{ $port.port }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
      name: {{ $port.name }}
    {{- end }}
  selector:
    {{- include "kink.worker.selectorLabels" . | nindent 4 }}

