{{- if and .Values.loadBalancer.enabled .Values.loadBalancer.manager.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kink.lb-manager.serviceAccountName" . }}
  labels:
    {{- include "kink.load-balancer.labels" . | nindent 4 }}
  {{- with .Values.loadBalancer.manager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
