name: Helm

on:
  workflow_dispatch: {}
  push:
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  CHART_DIR: helm/kink
  HELM_REPO: "oci://ghcr.io/${{ github.repository }}/charts"

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get Tag
        id: tagName
        uses: olegtarasov/get-tag@v2.1

      - name: Install Helm
        run:
          make helm
        
      - name: Lint
        run: |
          bin/helm lint "${CHART_DIR}"
          bin/helm template "${CHART_DIR}"

      # Release charts
      - name: Push Charts
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          set -x
          bin/helm registry login "${REGISTRY}" -u "${GITHUB_ACTOR}" -p "${GITHUB_TOKEN}"

          GIT_TAG="${{ steps.tagName.outputs.tag }}"
          if [ -n "${GIT_TAG}" ]; then
            ARGS=( CHART_VERSION="${GIT_TAG}" CHART_APP_VERSION="${GIT_TAG}" )
          else
            ARGS=( CHART_APP_VERSION="sha-${GITHUB_SHA}" CHART_GIT_SHA="${GITHUB_SHA}" )
          fi
          make chart "${ARGS[@]}"
          bin/helm push bin/charts/kink-*.tgz "${HELM_REPO}"

